
//! Autogenerated weights for pallet_computing_workers
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-11-23, STEPS: `50`, REPEAT: 50, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `Jasl-MBP2021-285.local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/research-node
// benchmark
// pallet
// --pallet=pallet_computing_workers
// --chain=dev
// --steps=50
// --repeat=50
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./pallets/computing_workers/src/weights.rs
// --template=./templates/pallet-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_computing_workers.
pub trait WeightInfo {
	fn register() -> Weight;
}

/// Weights for pallet_computing_workers using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: ComputingWorkers Workers (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ComputingWorkers CounterForWorkers (r:1 w:1)
	fn register() -> Weight {
		// Minimum execution time: 43_000 nanoseconds.
		Weight::from_ref_time(44_000_000)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: ComputingWorkers Workers (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: ComputingWorkers CounterForWorkers (r:1 w:1)
	fn register() -> Weight {
		// Minimum execution time: 43_000 nanoseconds.
		Weight::from_ref_time(44_000_000)
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
}
